---
- hosts: localhost
  gather_facts: true
  become: false
  vars:
    - test1: i have set this
  tasks:
    - name: test varible output
      debug:
#        msg: "test varible is it set? {{ test1 }} "
        msg: " {{  nsible_facts}} "

    - name: set stat teststat1
      set_stats:
        data:
          setstats_test1: "this is a set_stats"

    - name: set fact test1
      set_fact: 
        setfact_test: "this is a set_fact"

    - name: set_stats facts test
      set_stats:
        data:
          setstats_test2: "{{ ansible_facts }}"

    - name: Setting host facts using complex arguments
      set_fact:
        cache: yes
        one_fact: something
