---
- hosts: localhost
  gather_facts: true
  become: false
  vars:
    - test1: i have set this
  tasks:
    - name: test varible output
      debug:
        msg: "test varible is it set? {{ test1 }} "

    - name: set stat teststat1
      set_stats:
        data:
          setstats_test1: "this is a set_stats"
    - name: set fact test1
      set_fact:
        data:
          setfact_test1: "this is a set_fact"
